name: Resuable workflow for GitHub Actions
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the artifact to deploy
                required: true
                type: string
                default: dist
        outputs:
            deployed-artifact:
                description: "The name of the deployed artifact"
                value: ${{ jobs.deploy.outputs.outcome }}
        #secrets:
        #    some-secret:
        #       description: "A secret for deployment"
        #        required: false
jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-output.outputs.Step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name}}
            - name: list files
              run: ls 
            - name: Output Information
              run: |
                echo "Deploying to production..."
                echo "Artifact name: ${{ inputs.artifact-name }}"
            - name: Set output
              id: set-output
              run: echo "Step-result=success" >> $GITHUB_OUTPUT
                